name: Ingest Emails (cron)

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: {}

concurrency:
  group: ingest-cron
  cancel-in-progress: false

jobs:
  ingest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: backend/requirements.txt

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run ingestion script
        env:
          IMAP_HOST: ${{ secrets.IMAP_HOST }}
          IMAP_USER: ${{ secrets.IMAP_USER }}
          IMAP_PASS: ${{ secrets.IMAP_PASS }}
          IMAP_FOLDER: ${{ secrets.IMAP_FOLDER }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          PYTHONPATH: .
        run: python -m scripts.ingest_save_supabase

      - name: Done
        if: always()
        run: echo "Ingestion finished at $(date -u)"
